// Start pnpm dev, then run pnpm test:ui. Uses isolated browser storage; no backend.
import { chromium, expect } from "@playwright/test"

const base = process.env.SQUIG_TEST_URL ?? "http://localhost:3000"
const browser = await chromium.launch()
const errors = []
async function fixture(options = {}) {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, ...options })
  const page = await context.newPage()
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto(base)
  await page.waitForFunction(() => !!window.squig)
  return { context, page }
}

try {
  const { context, page } = await fixture()
  const font = page.getByRole("button", { name: "About Font", exact: true })
  const tooltip = page.getByRole("tooltip")
  await font.hover()
  // A brief pass must not flash help; intentional hover must reveal it.
  await page.waitForTimeout(250)
  await expect(tooltip).toHaveCount(0)
  await expect(tooltip).toHaveText("Saved per drawing; reused for new drawings.")
  await tooltip.hover()
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(tooltip).toHaveCount(0)

  await page.keyboard.press("Tab")
  await font.focus()
  await expect(font).toHaveAccessibleDescription("Saved per drawing; reused for new drawings.")
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(tooltip).toHaveCount(0)
  await expect(font).toBeFocused()
  await page.keyboard.press("Enter")
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Tab")
  await expect(tooltip).toHaveCount(0)

  await page.getByRole("button", { name: "Components", exact: true }).click()
  await expect(page.getByRole("textbox", { name: "Search components" })).toBeFocused()
  await page.getByRole("button", { name: "About Components" }).click()
  await expect(tooltip).toHaveText("Drag an item onto the canvas, or select it and click to place.")
  await page.getByRole("textbox", { name: "Search components" }).focus()
  await page.keyboard.press("Escape")

  await page.evaluate(() => window.squig.addComponent("navbar", { x: 200, y: 200 }))
  await expect(page.getByRole("textbox", { name: "Links", exact: true })).toHaveAccessibleDescription("Separate items with commas.")
  await page.getByRole("button", { name: "About Links", exact: true }).click()
  await expect(tooltip).toHaveText("Separate items with commas.")
  await page.keyboard.press("Escape")
  await page.evaluate(() => window.squig.addText("Hello", { x: 200, y: 400 }))
  await expect(page.getByRole("textbox", { name: "Font size", exact: true })).toBeVisible()
  await page.evaluate(() => window.squig.select([]))

  const searchTrigger = page.getByRole("button", { name: "Search ⌘K" })
  await searchTrigger.click()
  const search = page.getByRole("textbox", { name: "Search commands, layers, components, blocks, and icons" })
  const dialog = page.getByRole("dialog", { name: "Search Squig" })
  await expect(search).toBeFocused()
  await expect(page.locator("[inert]")).toHaveCount(1)
  await page.keyboard.press("Shift+Tab")
  expect(await dialog.evaluate((el) => el.contains(document.activeElement))).toBe(true)
  await page.keyboard.press("Tab")
  await expect(search).toBeFocused()
  await page.getByRole("button", { name: "About Help" }).focus()
  await expect(tooltip).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(tooltip).toHaveCount(0)
  await expect(dialog).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(dialog).toHaveCount(0)
  await expect(searchTrigger).toBeFocused()

  // A command that opens another dialog must not immediately close it again.
  await searchTrigger.click()
  await search.fill("Keyboard shortcuts")
  await page.keyboard.press("Enter")
  await expect(page.getByRole("dialog", { name: "Keyboard", exact: true })).toBeVisible()
  const close = page.getByRole("button", { name: "Close keyboard shortcuts" })
  await expect(close).toBeFocused()
  await page.keyboard.press("Shift+Tab")
  await expect(page.getByRole("region", { name: "Keyboard shortcuts" })).toBeFocused()
  await page.keyboard.press("Tab")
  await expect(close).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)

  await page.goto(`${base}/connect`)
  await expect(page.getByRole("heading", { name: "Connect your agent" })).toBeVisible()
  const config = page.locator("details").filter({ has: page.getByText("Manual Codex config", { exact: true }) })
  await expect(config.locator("pre")).not.toBeVisible()
  await config.locator("summary").focus()
  await page.keyboard.press("Enter")
  await expect(config.locator("pre")).toBeVisible()
  await expect(page.getByText("Agent canvases are saved online. Local drawings stay in this browser.")).toBeVisible()
  await context.close()

  const touch = await fixture({ hasTouch: true, reducedMotion: "reduce", viewport: { width: 390, height: 844 } })
  await touch.page.getByRole("button", { name: "About Font", exact: true }).tap()
  await expect(touch.page.getByRole("tooltip")).toHaveText("Saved per drawing; reused for new drawings.")
  expect(await touch.page.getByRole("tooltip").evaluate((el) => getComputedStyle(el).transitionProperty)).toBe("none")
  expect(await touch.page.getByRole("tooltip").evaluate((el) => getComputedStyle(el).transform)).toBe("none")
  const bounds = await touch.page.getByRole("tooltip").boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
  await touch.page.getByRole("heading", { name: "Page", exact: true }).tap()
  await expect(touch.page.getByRole("tooltip")).toHaveCount(0)
  await touch.context.close()
  expect(errors).toEqual([])
  console.log("UI helper checks passed: delayed/hoverable help, keyboard, touch, reduced motion, field descriptions, modal focus, setup disclosure.")
} finally {
  await browser.close()
}
